### ISSUE TITLE
InventoryPanel::_is_valid_filter could return wrong value

### ISSUE THREAD

**Issue by sadovsf** [GDQuest/godot-2d-builder#4]
So far how function is written now it only searches for any substring in filter string. This though could return false positive in case that given type is a substring of type in filter. As an example let's say there are two types `Coal` and `CompactedCoal` if you want to make machine (maybe same goes for recipes i did not check that case) that takes only `CompactedCoal` you are out of luck as `_filter.find("Coal")` search will be positive even though there is filter for `CompactedCoal` only.

Simple proposed solution would be to make filter either array of strings and do equal compare or split `_filter` string in `_ready` to make it a array so you can make whole filter little bit more strict.

I'am sorry if it is too soon to report such stuff. I just can't wait for course so i'am just going through code and thought processes behind commits trying out how stuff works in advance :D Looking forward to final tutorial :-) great work!

**Comment by Razoric480** [comment]
I had thought of the problem, but didn't come up with a great solution yet. Using `String.split` is a good solution, though. Thanks~

**Comment by sadovsf** [comment]
No problem, I will try to report stuff If I run into more. I managed to break inventory ui when I was playing with it as well (like no sprite item in backpack for example. Even crash once. But I don't have repro for these, I was just messing around for a minute or two when these happened)
