### ISSUE TITLE
Possible Blueprint leak in FurnaceGUI.gd

### ISSUE THREAD

**Issue by sadovsf** [GDQuest/godot-2d-builder#5]
In function `grab_output` is checking `held_item_id == item_id` but there is missing case what to do if not.

In simplest case `item.queue_free()` should be called for missing else code branch to release `BlueprintEntity`. Ideally some handling so player does not loose this prepared item.

**Comment by Razoric480** [comment]
I'll double check for missing edge cases with that function. Thanks.

**Comment by sadovsf** [comment]
No problem :-)
Maybe check out this place for other machines as they may contain this issue as well (i did not check them explicitly as code was not complete yet)
