### ISSUE TITLE
It is possible to open multiple machine GUIs at once

### ISSUE THREAD

**Issue by sadovsf** [GDQuest/godot-2d-builder#6]
When you click on machine backpack and machine GUI opens. Then when you click other machine (without closing previous one) it stacks on top of the previous one in same window :D
<img width="640" alt="Snímek obrazovky 2020-10-11 v 11 38 34" src="https://user-images.githubusercontent.com/2211533/95675293-63b9b380-0bb6-11eb-88a8-d173a73a172c.png">

**Repro steps:**
- Start game
- Build 2 machines
- Go to a place where you will be able to click on machines even when GUI is opened
- Click on ope machine to open its inventory
- Click on other machine (without closing previously opened GUI)
- DONE, you have both machine GUIs in single window

**Expected:**
GUI of previous machine should close before opening new one.

**Comment by sadovsf** [comment]
Also all GUIs opened after first one will remain in inventory when you go away and open it using `E` key

**Comment by Razoric480** [comment]
That's un-intentional. Thanks for reporting it~
