### ISSUE TITLE
Error when adding a Battery

### ISSUE THREAD

**Issue by pnadalini** [GDQuest/godot-2d-builder#7]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
When you run the project and add a Battery, the program crashes.

**What is the expected behavior?**
It should add the Battery object in the map.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Click on the start button
2. Grab the Battery from the bottom inventory
3. Place it anywhere on the map

The error occurs in `BatteryEntity.gd` in line 25
It tries to get the variable `_power_indicator` and it should be `_power_direction` according to the variables from that Entity.

**Comment by NathanLovato** [comment]
Just tested, I can confirm this. @Razoric480 may I let you look into it?

**Comment by Razoric480** [comment]
Thanks. Missed this in some of the refactor

**Comment by NathanLovato** [comment]
Thanks @pnadalini for reporting the issue, and thanks for the fix @Razoric480 !
